title: Акын Автоматика
description: Animus ante omnes. Cordis ante animus.
show_downloads: false
google_analytics:
theme: jekyll-theme-leap-day
# logo: "your_logo_path"
# favicon_ico: "your_icon_path"

navigation:
  - title: Home
    url: /
  - title: About
    url: /about/