title: "Акын Автоматика"
url: https://akyn-ai.github.io # site url # https://akyn-ai.com
baseurl: "" # apply repo name if use it under gh-pages branch

repo: https://github.com/akyn-ai/akyn-ai.github.io
comments: false

# remote_theme: mattcone/markdown-guide

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  # - jekyll-remote-theme

collections:
  basic-syntax:
  extended-syntax:
  tools:
    output: true
    permalink: /tools/:title/

defaults:
  - scope:
      type: tools
    values:
      layout: tool

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Author settings
author:
  name: "Акын Автоматики"

# social settings
og_locale: "en_US"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt", "Rakefile", "netlify.toml", "deploy.sh", "redirects.conf"]
